### ISSUE TITLE
[notice] Local에서 테스트를 위한  yml 설정 

### ISSUE THREAD

**Issue by dahxxn** [MetalRoze/OnlineNews_BE#23]
## 🔗현재 application.yml 파일 구조 
```
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

datasource:

cloud:
 
jwt:

server:
  port: 8080
```

### 2. connection 생성 후 onlinenews_db 스키마 생성하기 
<img width="242" alt="image" src="https://github.com/user-attachments/assets/bca2dc74-46cd-42f4-9a3c-d49ce08b6f51">
<img width="136" alt="image" src="https://github.com/user-attachments/assets/0c75a941-c2cb-4b11-bc84-15600f7a3cd0">

### 3. yml 파일을 아래와 같이 수정하기 
> url : jdbc:mysql://locahost:{포트번호}/onlinenews_db?serverTimezone=Asia/Seoul 

```
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onlinenews_db?serverTimezone=Asia/Seoul
    username: 
    password: 
```

username과 password는 각자 mysql workbench의 connection에 설정한 계정 root와 비번 설정해주면 됩니다.
