### ISSUE TITLE
Git 변경사항에 application.yml 추가 될때 처리법(추가되면 안됩니다~!) 

### ISSUE THREAD

**Issue by dahxxn** [MetalRoze/OnlineNews_BE#60]
```
git rm -r --cached .
git add .
git commit -m "fixed untracked files"
```

이거 콘솔에 입력하면 깃 이그노어 다시 적용된답니다.

**Comment by eunznidang** [comment]
### 기사본문 request를 위한 용량 설정

```
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
```

**Comment by dahxxn** [comment]
### 메일 발송을 위한 SMTP 설정 
spring: 하위에 추가해주세용 
```
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
```
